[package]
name = "numerics"
version = "0.1.0"
authors = ["Chris McDonald <mail.chris.mcdonald@gmail.com>"]

[dependencies]
nom = "^3"
rchunks = { git = "https://github.com/cjm00/rchunks" }

[features]
thicc_ints = []
bench = []